language: node_js
node_js:
  - "iojs-v1.8"
before_install:
  - cat /etc/apt/sources.list
  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ vivid main restricted"
  - cat /etc/apt/sources.list
  - sudo apt-get update
  - sudo rm /etc/dpkg/dpkg.cfg.d/multiarch
  - sudo apt-get install -y --force-yes libexpat1-dev libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
script:
  - npm run-script test-travis
notifications:
  irc:
    channels:
      - "irc.esper.net#crafatar"
    skip_join: true
services:
  - redis-server
cache:
  directories:
    - node_modules