language: node_js
node_js:
  - "0.10"
  - "0.12"
before_script:
  - cp "modules/config.example.js" "modules/config.js"
before_install:
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
notifications:
  irc:
    channels:
      - "irc.esper.net#crafatar"
    skip_join: true
services:
  - redis-server
