language: node_js
node_js:
  - iojs-v2.0
sudo: false
addons:
  apt:
    packages:
    - libcairo2-dev
    - libjpeg8-dev
    - libpango1.0-dev
    - libgif-dev
    - build-essential
    - g++
before_install:
  - mkdir -pv images/{faces,helms,skins,renders,capes}
  - sed -i.bak 's/\/var\/lib\/crafatar\///g' config.example.js
script:
  - npm run-script test-travis
notifications:
  irc:
    channels:
      - irc.esper.net#crafatar
    skip_join: true
env: TRAVIS=true
services:
  - redis-server
cache:
  directories:
    - node_modules